### ISSUE TITLE
How to get more debugin info ?

### ISSUE THREAD

**Issue by justgo97** [dreamstalker/rehlds#419]
```
----------------------------------------------
CRASH: Sat Mar 25 21:14:09 EDT 2017
Start Line: ./hlds_linux -game cstrike +ip xxxxxxxx +port 27015 +maxplayers 32 +map de_dust2 -pingboost 2 -debug -pidfile hlds.17141.pid
[New Thread 5600]
[New Thread 5626]
[New Thread 5637]
[New Thread 5673]
[New Thread 16824]
[New Thread 5624]
Core was generated by `./hlds_linux -game cstrike +ip xxxxxxxxx +port 27015 +maxplayers 32 +map d'.
Program terminated with signal 11, Segmentation fault.
#0  0x00ade939 in ?? ()
#0  0x00ade939 in ?? ()
No symbol table info available.
From        To          Syms Read   Shared Object Library
0x0023e830  0x002565cf  Yes (*)     /lib/ld-linux.so.2
(*): Shared library is missing debugging information.
Stack level 0, frame at 0xfffb18c4:
 eip = 0xade939; saved eip End of crash report
----------------------------------------------
```

**Comment by In-line** [comment]
Closing as non active.

**Comment by WaLkZa** [comment]
https://aghl.ru/forum/viewtopic.php?f=10&t=1441
