### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Sugisakii** [dreamstalker/rehlds#474]
```
Segmentation fault (core dumped)

"/home/ogp_agent/OGP_User_Files/1/./hlds_linux": not in executable format: File truncated

warning: Could not load shared library symbols for 2 libraries, e.g. /home/ogp_agent/OGP_User_Files/21/engine_i486.so.

Use the "info sharedlibrary" command to see the complete listing.

Do you need "set solib-search-path" or "set sysroot"?

email debug.log to linux@valvesoftware.com

Mon May 15 12:09:52 UTC 2017: Server restart in 10 seconds```

----------------------------------------------
CRASH: Mon May 15 12:12:08 UTC 2017
Start Line: ./hlds_linux -game cstrike -pidfile ogp_game_startup.pid +map de_dust2 +ip 10.142.0.3 +port 27015 +maxplayers 11
[New LWP 6134]
Core was generated by `./hlds_linux -game cstrike -pidfile ogp_game_startup.pid +map de_dust2 +ip 35.1'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf6ffc900 in ?? ()
#0  0xf6ffc900 in ?? ()
#1  0xf6ffae23 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
No symbol table info available.
From        To          Syms Read   Shared Object Library
0xf773c914  0xf7782c78  No          ./libstdc++.so.6
0xf76ebad0  0xf76ec96c  No          /lib32/libdl.so.2
0xf76d3840  0xf76e0217  No          /lib32/libpthread.so.0
0xf7539490  0xf7669f5e  No          /lib32/libc.so.6
0xf74e0600  0xf750e09b  No          /lib32/libm.so.6
0xf77cf860  0xf77e776c  No          /lib/ld-linux.so.2
0xf74c7e04  0xf74d7490  No          ./libgcc_s.so.1
                        No          /home/ogp_agent/OGP_User_Files/21/engine_i486.so
0xf6e6f9b0  0xf6e72f4a  No          /lib32/librt.so.1
0xf6e5d5c0  0xf6e67d74  No          ./libsteam_api.so
                        No          /home/ogp_agent/OGP_User_Files/21/filesystem_stdio.so
0xf5c1f300  0xf6932c44  No          ./steamclient.so
0xf5ace670  0xf5b44020  No          ./crashhandler.so
Stack level 0, frame at 0xff9fc920:
 eip = 0xf6ffc900; saved eip = 0xf6ffae23
 called by frame at 0x9
 Arglist at 0xff9fc918, args: 
 Locals at 0xff9fc918, Previous frame's sp is 0xff9fc920
 Saved registers:
  ebp at 0xff9fc918, eip at 0xff9fc91c
End of crash report
----------------------------------------------

**Comment by In-line** [comment]
This is awful. Read about markdown formatting
