### ISSUE TITLE
cant compile on armhf/armv7l(orange pi pc)

### ISSUE THREAD

**Issue by feskolech** [dreamstalker/rehlds#619]
Хз как компильнуть под orange pi, офк понимаю что поддержки не заявлено такой хрени, но мало ли че
`root@orangepipc:~/rehlds# gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`
`root@orangepipc:~/rehlds# javac -version
javac 1.8.0_171`

`root@orangepipc:~/rehlds# ./gradlew --max-workers=4 -PuseGcc clean buildFixes 
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar
Support for reading or changing file permissions is only available on this platform using Java 7 or later.
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
##teamcity[buildNumber '3.4.0.653']

FAILURE: Build failed with an exception.

* Where:
Script '/root/rehlds/shared.gradle' line: 34

* What went wrong:
A problem occurred configuring project ':dep/bzip2'.
> Exception thrown while executing model rule: org.gradle.nativeplatform.plugins.NativeComponentModelPlugin$Rules#createNativeBinaries(org.gradle.platform.base.BinaryContainer, org.gradle.api.NamedDomainObjectSet<org.gradle.nativeplatform.NativeComponentSpec>, org.gradle.language.base.internal.registry.LanguageTransformContainer, org.gradle.nativeplatform.toolchain.internal.NativeToolChainRegistryInternal, org.gradle.platform.base.internal.PlatformResolvers, org.gradle.nativeplatform.BuildTypeContainer, org.gradle.nativeplatform.FlavorContainer, org.gradle.internal.service.ServiceRegistry, java.io.File, org.gradle.api.internal.project.taskfactory.ITaskFactory)
   > Unknown native toolchain: org.gradle.nativeplatform.toolchain.internal.DefaultNativeToolChainRegistry$UnavailableNativeToolChain

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 38.945 secs`
with --stacktrace
`* What went wrong:
A problem occurred configuring project ':dep/bzip2'.
> Exception thrown while executing model rule: org.gradle.nativeplatform.plugins.NativeComponentModelPlugin$Rules#createNativeBinaries(org.gradle.platform.base.BinaryContainer, org.gradle.api.NamedDomainObjectSet<org.gradle.nativeplatform.NativeComponentSpec>, org.gradle.language.base.internal.registry.LanguageTransformContainer, org.gradle.nativeplatform.toolchain.internal.NativeToolChainRegistryInternal, org.gradle.platform.base.internal.PlatformResolvers, org.gradle.nativeplatform.BuildTypeContainer, org.gradle.nativeplatform.FlavorContainer, org.gradle.internal.service.ServiceRegistry, java.io.File, org.gradle.api.internal.project.taskfactory.ITaskFactory)
   > Unknown native toolchain: org.gradle.nativeplatform.toolchain.internal.DefaultNativeToolChainRegistry$UnavailableNativeToolChain

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':dep/bzip2'.
	at org.gradle.execution.TaskNameResolver.selfClosedTasksNode(TaskNameResolver.java:116)
	at org.gradle.execution.TaskNameResolver.hasTask(TaskNameResolver.java:128)
	at org.gradle.execution.TaskNameResolver.access$100(TaskNameResolver.java:38)
	at org.gradle.execution.TaskNameResolver$MultiProjectTaskSelectionResult.collect(TaskNameResolver.java:195)
	at org.gradle.execution.TaskNameResolver$MultiProjectTaskSelectionResult.collect(TaskNameResolver.java:203)
	at org.gradle.execution.TaskNameResolver$MultiProjectTaskSelectionResult.collectTasks(TaskNameResolver.java:191)
	at org.gradle.execution.TaskNameResolver.selectWithName(TaskNameResolver.java:61)
	at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:87)
	at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:75)
	at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(CommandLineTaskParser.java:42)
	at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:44)
	at org.gradle.execution.DefaultBuildExecuter.configure(DefaultBuildExecuter.java:42)
	at org.gradle.execution.DefaultBuildExecuter.access$100(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:48)
	at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
	at org.gradle.execution.DefaultBuildExecuter.configure(DefaultBuildExecuter.java:42)
	at org.gradle.execution.DefaultBuildExecuter.access$100(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:48)
	at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
	at org.gradle.execution.DefaultBuildExecuter.configure(DefaultBuildExecuter.java:42)
	at org.gradle.execution.DefaultBuildExecuter.select(DefaultBuildExecuter.java:35)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:142)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.model.internal.core.ModelRuleExecutionException: Exception thrown while executing model rule: org.gradle.nativeplatform.plugins.NativeComponentModelPlugin$Rules#createNativeBinaries(org.gradle.platform.base.BinaryContainer, org.gradle.api.NamedDomainObjectSet<org.gradle.nativeplatform.NativeComponentSpec>, org.gradle.language.base.internal.registry.LanguageTransformContainer, org.gradle.nativeplatform.toolchain.internal.NativeToolChainRegistryInternal, org.gradle.platform.base.internal.PlatformResolvers, org.gradle.nativeplatform.BuildTypeContainer, org.gradle.nativeplatform.FlavorContainer, org.gradle.internal.service.ServiceRegistry, java.io.File, org.gradle.api.internal.project.taskfactory.ITaskFactory)
	at org.gradle.model.internal.registry.DefaultModelRegistry.fireMutation(DefaultModelRegistry.java:555)
	at org.gradle.model.internal.registry.DefaultModelRegistry.fireMutations(DefaultModelRegistry.java:488)
	at org.gradle.model.internal.registry.DefaultModelRegistry.transition(DefaultModelRegistry.java:415)
	at org.gradle.model.internal.registry.DefaultModelRegistry.close(DefaultModelRegistry.java:374)
	at org.gradle.model.internal.registry.DefaultModelRegistry.closeRuleBinding(DefaultModelRegistry.java:582)
	at org.gradle.model.internal.registry.DefaultModelRegistry.toViews(DefaultModelRegistry.java:566)
	at org.gradle.model.internal.registry.DefaultModelRegistry.fireMutation(DefaultModelRegistry.java:542)
	at org.gradle.model.internal.registry.DefaultModelRegistry.fireMutations(DefaultModelRegistry.java:488)
	at org.gradle.model.internal.registry.DefaultModelRegistry.transition(DefaultModelRegistry.java:415)
	at org.gradle.model.internal.registry.DefaultModelRegistry.atStateOrMaybeLater(DefaultModelRegistry.java:237)
	at org.gradle.model.internal.registry.DefaultModelRegistry.atStateOrLater(DefaultModelRegistry.java:229)
	at org.gradle.execution.TaskNameResolver.selfClose(TaskNameResolver.java:101)
	at org.gradle.execution.TaskNameResolver.selfClosedTasksNode(TaskNameResolver.java:114)
	... 48 more
Caused by: java.lang.RuntimeException: Unknown native toolchain: org.gradle.nativeplatform.toolchain.internal.DefaultNativeToolChainRegistry$UnavailableNativeToolChain
	at shared_3ddbttk9bcm4pqlo3369mwkr9$_run_closure1.doCall(/root/rehlds/shared.gradle:34)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:159)
	at org.gradle.api.internal.project.DefaultProject_Decorated.invokeMethod(Unknown Source)
	at build_9tuf2qdkgmc89qcbz4bocu65p.setupToolchain(/root/rehlds/dep/bzip2/build.gradle:16)
	at org.gradle.api.internal.BeanDynamicObject$GroovyObjectAdapter.invokeMethod(BeanDynamicObject.java:275)
	at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:127)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
	at org.gradle.api.internal.project.DefaultProject_Decorated.invokeMethod(Unknown Source)
	at build_9tuf2qdkgmc89qcbz4bocu65p$_run_closure1_closure5_closure7_closure9.doCall(/root/rehlds/dep/bzip2/build.gradle:76)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
	at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:165)
	at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:159)
	at org.gradle.nativeplatform.internal.configure.DefaultNativeBinariesFactory.createNativeBinary(DefaultNativeBinariesFactory.java:56)
	at org.gradle.nativeplatform.internal.configure.DefaultNativeBinariesFactory.createNativeBinaries(DefaultNativeBinariesFactory.java:46)
	at org.gradle.nativeplatform.internal.configure.NativeComponentSpecInitializer.executeForEachFlavor(NativeComponentSpecInitializer.java:99)
	at org.gradle.nativeplatform.internal.configure.NativeComponentSpecInitializer.executeForEachBuildType(NativeComponentSpecInitializer.java:91)
	at org.gradle.nativeplatform.internal.configure.NativeComponentSpecInitializer.execute(NativeComponentSpecInitializer.java:69)
	at org.gradle.nativeplatform.internal.configure.NativeComponentSpecInitializer.execute(NativeComponentSpecInitializer.java:40)
	at org.gradle.nativeplatform.plugins.NativeComponentModelPlugin$Rules.createNativeBinaries(NativeComponentModelPlugin.java:166)
	at org.gradle.model.internal.method.WeaklyTypeReferencingMethod.invoke(WeaklyTypeReferencingMethod.java:101)
	at org.gradle.model.internal.inspect.DefaultModelRuleInvoker.invoke(DefaultModelRuleInvoker.java:37)
	at org.gradle.model.internal.inspect.MethodBackedModelAction.execute(MethodBackedModelAction.java:63)
	at org.gradle.model.internal.registry.DefaultModelRegistry.fireMutation(DefaultModelRegistry.java:552)
	... 60 more`

**Comment by lastuniverse** [comment]
+

feskolech, смог решить проблему?

**Comment by feskolech** [comment]
@lastuniverse не, чувак, быстро забил

**Comment by bobbibob** [comment]
> I have the same question!!!
> 
> feskolech, смог решить проблему?

В файле shared.gradle 

		throw new RuntimeException("Unknown native toolchain: ${bin.toolChain.class.name}")

Поменяй на 

return rootProject.createGccConfig(releaseBuild, binaryKind)
