### ISSUE TITLE
Does not compile with the latest version of OpenJDK

### ISSUE THREAD

**Issue by the-swank** [dreamstalker/rehlds#651]
`swank@home ~/p/rehlds> javac -version`

> javac 10.0.2

`swank@home ~/p/rehlds> gcc --version`

> gcc (GCC) 8.2.1 20180831
> Copyright © 2018 Free Software Foundation, Inc.
> Це програмне забезпечення є вільним, умови копіювання викладено у його
> початкових кодах.
> Умовами ліцензування програми НЕ передбачено жодних гарантій, зокрема
> гарантій працездатності або придатності для певної мети.
> 

`swank@home ~/p/rehlds> ./gradlew --max-workers=1 -PuseGcc clean buildRelease`

> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine java version from '10.0.2'.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

`swank@home ~/p/rehlds> ./gradlew --max-workers=1 --stacktrace --debug -PuseGcc clean buildRelease`

> 16:33:19.693 [DEBUG] [org.gradle.internal.nativeintegration.services.NativeServices] Unable to load from native-platform backed ConsoleDetector. Continuing with fallback. Failure: net.rubygrapefruit.platform.NativeException: Failed to load native library 'libnative-platform-curses.so' for Linux amd64.
> caused by: java.lang.UnsatisfiedLinkError: /home/swank/.gradle/native/19/linux-amd64/libnative-platform-curses.so: libncurses.so.5: не вдалося відкрити файл об’єктів спільного використання: Немає такого файла або каталогу
> 16:33:19.732 [ERROR] [org.gradle.BuildExceptionReporter] 
> 16:33:19.735 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
> 16:33:19.735 [ERROR] [org.gradle.BuildExceptionReporter] 
> 16:33:19.736 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
> 16:33:19.736 [ERROR] [org.gradle.BuildExceptionReporter] Could not determine java version from '10.0.2'.
> 16:33:19.737 [ERROR] [org.gradle.BuildExceptionReporter] 
> 16:33:19.738 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
> 16:33:19.739 [ERROR] [org.gradle.BuildExceptionReporter] java.lang.IllegalArgumentException: Could not determine java version from '10.0.2'.
> 16:33:19.739 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:63)
> 16:33:19.740 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.JavaVersion.current(JavaVersion.java:72)
> 16:33:19.740 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
> 16:33:19.740 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
> 16:33:19.741 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
> 16:33:19.741 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
> 16:33:19.741 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
> 16:33:19.742 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
> 16:33:19.742 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.Main.doAction(Main.java:33)
> 16:33:19.742 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
> 16:33:19.743 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 16:33:19.743 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 16:33:19.743 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 16:33:19.744 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> 16:33:19.744 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
> 16:33:19.745 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
> 16:33:19.745 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
> 16:33:19.746 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 16:33:19.746 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 16:33:19.747 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 16:33:19.747 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> 16:33:19.748 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
> 16:33:19.748 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
> 16:33:19.749 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> 16:33:19.749 [ERROR] [org.gradle.BuildExceptionReporter]

**Comment by vitor-github** [comment]
What distro? I've been able to compile with JDK 7 and 8, never tried 10.
Try removing your JDK and gradle, then install gradle. It should prompt you with which JDK version you want to install

**Comment by In-line** [comment]
JDK 10 is not supported by old gradle.
