### ISSUE TITLE
dont compile to gcc v8.2.0

### ISSUE THREAD

**Issue by neygomon** [dreamstalker/rehlds#664]
fucking failed compile
GCC v8.2.0

`The current ReHLDS maven version is 3.4.0.668-dev, url: (https://github.com/dreamstalker/rehlds/commit/89be216)
:rehlds:compileReleaseRehldsFixesRehlds_swds_engineSharedLibraryRehlds_swds_engineRehlds_common
In file included from /usr/include/c++/8/stdlib.h:36,
                 from /home/neygomon/rehlds/rehlds/public/rehlds/osconfig.h:37,
                 from /home/neygomon/rehlds/rehlds/rehlds/precompiled.h:5,
                 from /home/neygomon/rehlds/rehlds/common/BaseSystemModule.cpp:29:
/usr/include/c++/8/cstdlib:41:10: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.

In file included from /usr/include/c++/8/stdlib.h:36,
                 from /home/neygomon/rehlds/rehlds/public/rehlds/osconfig.h:37,
                 from /home/neygomon/rehlds/rehlds/rehlds/precompiled.h:5,
                 from /home/neygomon/rehlds/rehlds/common/ObjectList.cpp:29:
/usr/include/c++/8/cstdlib:41:10: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.

In file included from /usr/include/c++/8/stdlib.h:36,
                 from /home/neygomon/rehlds/rehlds/public/rehlds/osconfig.h:37,
                 from /home/neygomon/rehlds/rehlds/rehlds/precompiled.h:5,
                 from /home/neygomon/rehlds/rehlds/common/TokenLine.cpp:1:
/usr/include/c++/8/cstdlib:41:10: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.

:rehlds:compileReleaseRehldsFixesRehlds_swds_engineSharedLibraryRehlds_swds_engineRehlds_common FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rehlds:compileReleaseRehldsFixesRehlds_swds_engineSharedLibraryRehlds_swds_engineRehlds_common'.
> Multiple build operations failed.
      C++ compiler failed while compiling BaseSystemModule.cpp.
      C++ compiler failed while compiling ObjectList.cpp.
      C++ compiler failed while compiling TokenLine.cpp.
  See the complete log at: file:///home/neygomon/rehlds/rehlds/build/tmp/compileReleaseRehldsFixesRehlds_swds_engineSharedLibraryRehlds_swds_engineRehlds_common/output.txt

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':rehlds:compileReleaseRehldsFixesRehlds_swds_engineSharedLibraryRehlds_swds_engineRehlds_common'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.internal.operations.MultipleBuildOperationFailures: Multiple build operations failed.
    C++ compiler failed while compiling BaseSystemModule.cpp.
    C++ compiler failed while compiling ObjectList.cpp.
    C++ compiler failed while compiling TokenLine.cpp.
See the complete log at: file:///home/neygomon/rehlds/rehlds/build/tmp/compileReleaseRehldsFixesRehlds_swds_engineSharedLibraryRehlds_swds_engineRehlds_common/output.txt
        at org.gradle.internal.operations.DefaultBuildOperationQueue.waitForCompletion(DefaultBuildOperationQueue.java:72)
        at org.gradle.nativeplatform.toolchain.internal.NativeCompiler.execute(NativeCompiler.java:73)
        at org.gradle.nativeplatform.toolchain.internal.NativeCompiler.execute(NativeCompiler.java:39)
        at org.gradle.nativeplatform.toolchain.internal.OutputCleaningCompiler.compileSources(OutputCleaningCompiler.java:46)
        at org.gradle.nativeplatform.toolchain.internal.OutputCleaningCompiler.execute(OutputCleaningCompiler.java:38)
        at org.gradle.nativeplatform.toolchain.internal.OutputCleaningCompiler.execute(OutputCleaningCompiler.java:26)
        at org.gradle.language.nativeplatform.internal.incremental.IncrementalNativeCompiler.doCleanIncrementalCompile(IncrementalNativeCompiler.java:96)
        at org.gradle.language.nativeplatform.internal.incremental.IncrementalNativeCompiler.execute(IncrementalNativeCompiler.java:74)
        at org.gradle.language.nativeplatform.internal.incremental.IncrementalNativeCompiler.execute(IncrementalNativeCompiler.java:37)
        at org.gradle.nativeplatform.internal.BuildOperationLoggingCompilerDecorator.execute(BuildOperationLoggingCompilerDecorator.java:38)
        at org.gradle.nativeplatform.internal.BuildOperationLoggingCompilerDecorator.execute(BuildOperationLoggingCompilerDecorator.java:22)
        at org.gradle.language.nativeplatform.tasks.AbstractNativeCompileTask.doCompile(AbstractNativeCompileTask.java:115)
        at org.gradle.language.nativeplatform.tasks.AbstractNativeCompileTask.compile(AbstractNativeCompileTask.java:107)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:243)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:230)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 49 more
Caused by: org.gradle.nativeplatform.toolchain.internal.CommandLineToolInvocationFailure: C++ compiler failed while compiling BaseSystemModule.cpp.
        at org.gradle.nativeplatform.toolchain.internal.DefaultCommandLineToolInvocationWorker.execute(DefaultCommandLineToolInvocationWorker.java:83)
        at org.gradle.nativeplatform.toolchain.internal.DefaultCommandLineToolInvocationWorker.execute(DefaultCommandLineToolInvocationWorker.java:30)
        at org.gradle.internal.operations.DefaultBuildOperationQueue$OperationHolder.run(DefaultBuildOperationQueue.java:110)
        at org.gradle.internal.concurrent.ExecutorPolicy$PropagateFailures.onExecute(ExecutorPolicy.java:76)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)

BUILD FAILED

Total time: 14.15 secs`

**Comment by welcoman** [comment]
Didn't try compiling with gcc v8.2.0, but it's fine with 8.2.1 - BUILD SUCCESSFUL
