### ISSUE TITLE
Server infinite looping (not crash)

### ISSUE THREAD

**Issue by wopox1337** [dreamstalker/rehlds#669]
> Noticed this afternoon that the server does not respond to _A2S__ requests, decided to check from the console - as a result - HLDS costs hung (loop).

> Why say _htop_:
![image](https://user-images.githubusercontent.com/18553678/47430234-7821fd00-d7a1-11e8-8bf2-91bb6a0db78c.png)
Lastest HLDS console log:
![image](https://user-images.githubusercontent.com/18553678/47430382-c800c400-d7a1-11e8-862e-57a318a921fc.png)

**Start Line:**
`Start Line: ./hlds_linux -game czero -strictportbind +ip <_SOME_SERVER_IP> -port 27025 +clientport 27005 +map de_dust2_cz -maxplayers 16`
**version**
```
Protocol version 48
Exe version 1.0.0.3/Stdio (czero)
ReHLDS version: 3.4.0.668-dev
Build date: 09:47:42 Sep 29 2018 (1631)
Build from: https://github.com/dreamstalker/rehlds/commit/89be216
```
**game version**
```
ReGameDLL version: 5.7.0.314-dev
Build date: 10:33:17 Oct  5 2018
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/7aeca16
```
**meta version**
```
Metamod-r v1.3.0.128, API (5:13)
Metamod-r build: 17:47:54 Aug 24 2018
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/0cf2f70
```

**meta list**
```
Currently loaded plugins:
      description   stat pend  file                      vers          src  load  unload
 [ 1] AMX Mod X     RUN   -    amxmodx_mm_i386.so        v1.10.0.5238  ini  Start ANY
 [ 2] FakeMeta      RUN   -    fakemeta_amxx_i386.so     v1.10.0.5238  pl1  ANY   ANY
 [ 3] CStrike       RUN   -    cstrike_amxx_i386.so      v1.10.0.5238  pl1  ANY   ANY
 [ 4] Ham Sandwich  RUN   -    hamsandwich_amxx_i386.so  v1.10.0.5238  pl1  ANY   ANY
 [ 5] CSX           RUN   -    csx_amxx_i386.so          v1.10.0.5238  pl1  ANY   ANY
5 plugins, 5 running
```
**meta config**
```
Config options from localinfo and /home/csserv/server/serverfiles/czero/addons/metamod/config.ini:
   debuglevel           0
   gamedll
   exec_cfg
   clientmeta           false
   dynalign_list        true
```
**amxx version**
```
AMX Mod X 1.10.0.5238 (http://www.amxmodx.org)
Authors:
        David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
        Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
        Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
        Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Oct 14 2018 08:46:07
Built from: https://github.com/alliedmodders/amxmodx/commit/77eb33d
Build ID: 5238:77eb33d
Core mode: JIT+ASM32
```

**amxx list**
```
Currently loaded plugins:
       name                    version     author            file             status
 [  1] Admin Base              1.10.0.523  AMXX Dev Team     admin.amxx       running
 [  2] Admin Commands          1.10.0.523  AMXX Dev Team     admincmd.amxx    running
 [  3] Slots Reservation       1.10.0.523  AMXX Dev Team     adminslots.amxx  running
 [  4] Multi-Lingual System    1.10.0.523  AMXX Dev Team     multilingual.am  running
 [  5] Menus Front-End         1.10.0.523  AMXX Dev Team     menufront.amxx   running
 [  6] Commands Menu           1.10.0.523  AMXX Dev Team     cmdmenu.amxx     running
 [  7] Players Menu            1.10.0.523  AMXX Dev Team     plmenu.amxx      running
 [  8] Teleport Menu           1.10.0.523  AMXX Dev Team     telemenu.amxx    running
 [  9] Maps Menu               1.10.0.523  AMXX Dev Team     mapsmenu.amxx    running
 [ 10] Plugin Menu             1.10.0.523  AMXX Dev Team     pluginmenu.amxx  running
 [ 11] Admin Chat              1.10.0.523  AMXX Dev Team     adminchat.amxx   running
 [ 12] Anti Flood              1.10.0.523  AMXX Dev Team     antiflood.amxx   running
 [ 13] Admin Votes             1.10.0.523  AMXX Dev Team     adminvote.amxx   running
 [ 14] Pause Plugins           1.10.0.523  AMXX Dev Team     pausecfg.amxx    running
 [ 15] Stats Configuration     1.10.0.523  AMXX Dev Team     statscfg.amxx    running
 [ 16] Restrict Weapons        1.10.0.523  AMXX Dev Team     restmenu.amxx    running
 [ 17] StatsX                  1.10.0.523  AMXX Dev Team     statsx.amxx      running
 [ 18] CS Misc. Stats          1.10.0.523  AMXX Dev Team     miscstats.amxx   running
 [ 19] CS Stats Logging        1.10.0.523  AMXX Dev Team     stats_logging.a  running
 [ 20] Map Manager: Core       3.0.1       Mistrick          map_manager_cor  running
 [ 21] Map Manager: Scheduler  0.1.0       Mistrick          map_manager_sch  running
 [ 22] Map Manager: Rtv        0.0.4       Mistrick          map_manager_rtv  running
 [ 23] Map Manager: Nominatio  0.0.8       Mistrick          map_manager_nom  running
 [ 24] Map Manager: BlockList  0.0.3       Mistrick          map_manager_blo  running
 [ 25] Map Manager: Online so  0.0.2       Mistrick          map_manager_onl  running
 [ 26] Map Manager: Informer   0.0.5       Mistrick          map_manager_inf  running
26 plugins, 26 running
```
### **[CVar list log](https://gist.github.com/wopox1337/c40f95dd07fccd9e37c74c48ef96350b)**
Plugins: [MapManager Modular](https://github.com/Mistrick/MapManagerModular) by @Mistrick

**from gdb:**
```
#0  0xf6da6734 in SV_ClipToLinks () from /home/csserv/server/serverfiles/engine_i486.so
#1  0x3ec05397 in ?? ()
#2  0xf6e1bacf in SV_RecursiveHullCheck () from /home/csserv/server/serverfiles/engine_i486.so
```

Estimated cause of the hang - this lines https://github.com/dreamstalker/rehlds/blob/65c6ce593b5eabf13e92b03352e4b429d0d797b0/rehlds/engine/world.cpp#L1452

**Comment by wopox1337** [comment]
Now i see same freeze (looping). But i disabled metamod...
![image](https://user-images.githubusercontent.com/18553678/47460608-8dba1580-d7e7-11e8-991b-c95d9fa9e491.png)

**Comment by wopox1337** [comment]
outdated. Closed
