### ISSUE TITLE
Server Crash on CS 1.6

### ISSUE THREAD

**Issue by mdlateef** [dreamstalker/rehlds#752]
Debug LOG
----------------------------------------------
CRASH: Thu Mar  5 20:22:14 IST 2020
Start Line: ./hlds_linux -game cstrike -strictportbind +ip 172.26.7.42 -port 11111 +clientport 27005 +map awp_india +servercfgfile csserver.cfg -maxplayers 20 +sys_ticrate 1024 -pingboost 2 -debug -pidfile hlds.1463.pid
[New LWP 3539]
[New LWP 3540]
[New LWP 3541]
[New LWP 3543]
[New LWP 3547]
[New LWP 3548]
[New LWP 3549]
[New LWP 3550]
[New LWP 3554]
Core was generated by `./hlds_linux -game cstrike -strictportbind +ip 172.26.7.42 -port 11111 +clientp'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf2445ec1 in ?? ()
[Current thread is 1 (LWP 3539)]
#0  0xf2445ec1 in ?? ()
Backtrace stopped: Cannot access memory at address 0xffd0fa50
No symbol table info available.
No shared libraries loaded at this time.
Stack level 0, frame at 0xffd0fa54:
 eip = 0xf2445ec1; saved eip = <error: Cannot access memory at address 0xffd0fa50>
 Outermost frame: Cannot access memory at address 0xffd0fa50
 Arglist at 0xffd0fa4c, args: 
 Locals at 0xffd0fa4c, Previous frame's sp is 0xffd0fa54
End of crash report
----------------------------------------------
Console LOG

Segmentation fault (core dumped)
BFD: Warning: /home/exzawp/serverfiles/core is truncated: expected core file size >= 206102528, found: 2985984.
Cannot access memory at address 0xf77ed908
Cannot access memory at address 0xf77ed904
Failed to read a valid object file image from memory.
Cannot access memory at address 0xf77ed908
Cannot access memory at address 0xf77ed904
debug.cmds:4: Error in sourced command file:
Cannot access memory at address 0xfff2aa50
email debug.log to linux@valvesoftware.com
Thu Mar  5 19:28:39 IST 2020: Server restart in 10 seconds

Segmentation fault (core dumped)
BFD: Warning: /home/exzawp/serverfiles/core is truncated: expected core file size >= 179208192, found: 2994176.
Cannot access memory at address 0xf77e6908
Cannot access memory at address 0xf77e6904
Failed to read a valid object file image from memory.
Cannot access memory at address 0xf77e6908
Cannot access memory at address 0xf77e6904
debug.cmds:4: Error in sourced command file:
Cannot access memory at address 0xffae6250
email debug.log to linux@valvesoftware.com
Thu Mar  5 19:29:12 IST 2020: Server restart in 10 seconds

ReHLDS version: 3.7.0.693-dev
ReGameDLL version: 5.14.0.453-dev+m
AMX Mod X 1.9.0.5263 
Reunion - v0.1.0.135

**Comment by WhiteFang1319** [comment]
Not sure where to actually post so I suggest my friend to post here. Someone's been crashing servers. Don't know how. I wasn't able to take log of my server but he was able one of his. The guy connects to the server and does something, then the server crashes. I'm using -condebug but it showed nothing in console log or sys_error.log file. Can somebody check this please?
