### ISSUE TITLE
Random crashes latest rehlds Cache_Alloc on mapchange

### ISSUE THREAD

**Issue by natashasrcz** [dreamstalker/rehlds#960]
I am using latest as per today rehlds (commit 17964599538cab2edbf5bbbdac52171b9917670a), compiled with gcc on debian 11.

CS 1.6 crashes randomly on map change (cannot cache models [Cache_Alloc ]? crashes with different models, so this is not custom model problem as they worked fine over 2 years, and they work fine in Condition Zero with the same rehlds version).
Below please find debug log (DDEBUG=ON, amxmodx debug ON, gdb installed).

```
CRASH: Sun 26 Mar 2023 04:04:50 PM CEST
Start Line: ./hlds_linux -game cstrike -console +ip 0.0.0.0 -secure -sv_lan 0 -port 27020 -noipx +maxplayers 24 -heapsize 1048576 -tos -pingboost 3 -strictportbind -debug -pidfile hlds.28202.pid
[New LWP 28220]
[New LWP 28222]
[New LWP 28228]
[New LWP 28225]
[New LWP 28221]
[New LWP 28230]
[New LWP 28226]
[New LWP 28229]
[New LWP 28233]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./hlds_linux -game cstrike -console +ip 0.0.0.0 -secure -sv_lan 0 -port 27020 -'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  Cache_TryAlloc (nobottom=0, size=3641808) at /home/natasha/rehlds/rehlds/engine/zone.cpp:647
647                     newmem = (cache_system_t *)((char *)cs + cs->size);
[Current thread is 1 (Thread 0xf7ba6700 (LWP 28220))]
#0  Cache_TryAlloc (nobottom=0, size=3641808) at /home/natasha/rehlds/rehlds/engine/zone.cpp:647
#1  Cache_Alloc (c=0xf79117d4 <mod_known+12148>, size=3641708, name=0xf7911650 <mod_known+11760> "models/player/fat_te/fat_te.mdl") at /home/natasha/rehlds/rehlds/engine/zone.cpp:847
#2  0xf75658b1 in Mod_LoadStudioModel_internal (mod=0xf7911650 <mod_known+11760>, buffer=0xe7549010) at /home/natasha/rehlds/rehlds/engine/l_studio.cpp:54
#3  0xf7565a6b in IVoidHookChainImpl<model_s*, void*>::callNext (args#1=<optimized out>, args#0=<optimized out>, this=<synthetic pointer>) at /home/natasha/rehlds/rehlds/rehlds/hookchains_impl.h:90
#4  0xf751e9e3 in Mod_LoadModel (mod=mod@entry=0xf7911650 <mod_known+11760>, crash=crash@entry=1, trackCRC=trackCRC@entry=0) at /home/natasha/rehlds/rehlds/engine/model.cpp:354
#5  0xf751ed19 in Mod_LoadModel (trackCRC=0, crash=1, mod=0xf7911650 <mod_known+11760>) at /home/natasha/rehlds/rehlds/engine/model.cpp:270
#6  Mod_Extradata (mod=0xf7911650 <mod_known+11760>) at /home/natasha/rehlds/rehlds/engine/model.cpp:77
#7  0xf74dab3a in PrecacheModelSpecifiedFiles () at /home/natasha/rehlds/rehlds/engine/sv_main.cpp:5816
#8  0xf74dae80 in SV_ActivateServer_internal (runPhysics=1) at /home/natasha/rehlds/rehlds/engine/sv_main.cpp:5881
#9  0xf74fe1cf in Host_Changelevel_f () at /home/natasha/rehlds/rehlds/engine/host_cmd.cpp:995
#10 0xf7526885 in Cmd_ExecuteString_internal (cmdName=0xed5e1698 "changelevel", src=src_command, client=0x0) at /home/natasha/rehlds/rehlds/engine/cmd.cpp:951
#11 0xf7526c85 in IVoidHookChainImpl<char const*, cmd_source_s, IGameClient*>::callNext (args#2=0x0, args#1=src_command, args#0=<optimized out>, this=<synthetic pointer>) at /home/natasha/rehlds/rehlds/rehlds/hookchains_impl.h:79
#12 IVoidHookChainImpl<char const*, cmd_source_s, IGameClient*>::callNext (args#2=0x0, args#1=src_command, args#0=<optimized out>, this=<synthetic pointer>) at /home/natasha/rehlds/rehlds/rehlds/hookchains_impl.h:79
#13 IVoidHookChainRegistryImpl<char const*, cmd_source_s, IGameClient*>::callChain (args#2=0x0, args#1=src_command, args#0=<optimized out>, origFunc=0xf7526830 <Cmd_ExecuteString_internal(char const*, cmd_source_s, IGameClient*)>, this=<optimized out>) at /home/natasha/rehlds/rehlds/rehlds/hookchains_impl.h:150
#14 Cmd_ExecuteString (text=0xff8ce6b0 "changelevel de_eldorado", src=src_command) at /home/natasha/rehlds/rehlds/engine/cmd.cpp:1005
#15 Cmd_ExecuteString (src=src_command, text=0xff8ce6b0 "changelevel de_eldorado") at /home/natasha/rehlds/rehlds/engine/cmd.cpp:991
#16 Cbuf_Execute () at /home/natasha/rehlds/rehlds/engine/cmd.cpp:238
#17 0xf74fc710 in _Host_Frame (time=0.00246232492) at /home/natasha/rehlds/rehlds/engine/host.cpp:882
#18 0xf74fca4f in Host_Frame (time=0.00246232492, iState=1, stateInfo=0xff8ceb6c) at /home/natasha/rehlds/rehlds/engine/host.cpp:960
#19 0xf74f7c57 in CEngine::Frame (this=0xf78dcd80 <g_Engine>) at /home/natasha/rehlds/rehlds/engine/sys_engine.cpp:119
#20 0xf74f6cd0 in CDedicatedServerAPI::RunFrame (this=<optimized out>) at /home/natasha/rehlds/rehlds/engine/sys_dll2.cpp:702
#21 CDedicatedServerAPI::RunFrame (this=0xf78dc880 <__g_CDedicatedServerAPI_singleton>) at /home/natasha/rehlds/rehlds/engine/sys_dll2.cpp:697
#22 0x08049df5 in RunEngine () at /home/natasha/rehlds/rehlds/dedicated/src/sys_ded.cpp:176
#23 0x08049fff in StartServer (cmdline=0x80542a0 <linuxCmdline> "-game cstrike -console +ip 0.0.0.0 -secure -sv_lan 0 -port 27020 -noipx +maxplayers 24 -heapsize 1048576 -tos -pingboost 3 -strictportbind -debug -pidfile hlds.28202.pid") at /home/natasha/rehlds/rehlds/dedicated/src/sys_ded.cpp:279
#24 0x0804949f in main (argc=23, argv=0xff8cee04) at /home/natasha/rehlds/rehlds/dedicated/src/sys_linux.cpp:344
cs = 0x6f7e7b95
newmem = 0xe8fc920e
cs = <optimized out>
newmem = <optimized out>
__func__ = {<optimized out> <repeats 15 times>}
From        To          Syms Read   Shared Object Library
0xf7f7e130  0xf7f7f304  Yes (*)     /lib/i386-linux-gnu/libdl.so.2
0xf7ef0914  0xf7f36c78  Yes         ./libstdc++.so.6
0xf7cda0f0  0xf7e2d4a6  Yes (*)     /lib/i386-linux-gnu/libc.so.6
0xf7f99090  0xf7fb5dd3  Yes (*)     /lib/ld-linux.so.2
0xf7bc7190  0xf7c87511  Yes (*)     /lib/i386-linux-gnu/libm.so.6
0xf7ba9e04  0xf7bb9490  Yes         ./libgcc_s.so.1
0xf74c8170  0xf7589713  Yes         /home/natasha/hlds_cs/engine_i486.so
0xf747a3d0  0xf747e0a4  Yes (*)     /lib/i386-linux-gnu/librt.so.1
0xf74675c0  0xf7471d74  Yes (*)     ./libsteam_api.so
0xf74485b0  0xf74588b4  Yes (*)     /lib/i386-linux-gnu/libpthread.so.0
0xf7429720  0xf74369c8  Yes         /home/natasha/hlds_cs/filesystem_stdio.so
0xf5755000  0xf6c361b4  Yes (*)     /home/natasha/SteamCMD/linux32/steamclient.so
0xf55e7ee0  0xf56299d4  Yes (*)     /home/natasha/SteamCMD/linux32/crashhandler.so
0xed3ed750  0xed511eb0  Yes         /home/natasha/hlds_cs/./cstrike/dlls/cs.so
0xed24bd00  0xed2f0ebc  Yes (*)     /home/natasha/hlds_cs/./cstrike/addons/metamod/dlls/metamod.so
0xed129a00  0xed189768  Yes (*)     /home/natasha/hlds_cs/cstrike/addons/amxmodx/dlls/amxmodx_mm_i386.so
0xed10ac10  0xed10dc98  Yes (*)     cstrike/addons/amxmodx/modules/fun_amxx_i386.so
0xed1000d0  0xed105408  Yes (*)     cstrike/addons/amxmodx/modules/geoip_amxx_i386.so
0xecea2220  0xecea89d8  Yes (*)     cstrike/addons/amxmodx/modules/cstrike_amxx_i386.so
0xece2dd50  0xece34658  Yes (*)     cstrike/addons/amxmodx/modules/csx_amxx_i386.so
0xecd0c3c0  0xecdf7b2d  Yes (*)     /home/natasha/hlds_cs/cstrike/addons/yapb/bin/yapb.so
0xeca780d0  0xeca83478  Yes (*)     cstrike/addons/amxmodx/modules/engine_amxx_i386.so
0xeca2ec50  0xeca5b4a8  Yes (*)     cstrike/addons/amxmodx/modules/fakemeta_amxx_i386.so
0xec9e3870  0xeca0f0b8  Yes (*)     cstrike/addons/amxmodx/modules/hamsandwich_amxx_i386.so
0xec9c9130  0xec9d4204  Yes (*)     cstrike/addons/amxmodx/modules/csdm_amxx_i386.so
0xea9fb000  0xec04c024  Yes (*)     ./steamclient.so
0xea028670  0xea09e020  Yes (*)     ./crashhandler.so
0xec9a4300  0xec9aa8c4  Yes (*)     /lib/i386-linux-gnu/libnss_files.so.2
0xea01b1c0  0xea01dea4  Yes (*)     /lib/i386-linux-gnu/libnss_dns.so.2
0xea0033b0  0xea00fc64  Yes (*)     /lib/i386-linux-gnu/libresolv.so.2
0xe8274c90  0xe8373644  Yes (*)     /lib/i386-linux-gnu/libSDL2-2.0.so.0
0xe8169d20  0xe81fd304  Yes (*)     /lib/i386-linux-gnu/libasound.so.2
0xe9d157a0  0xe9d44094  Yes (*)     /lib/i386-linux-gnu/libpulse.so.0
0xe800c910  0xe80984e4  Yes (*)     /lib/i386-linux-gnu/libX11.so.6
0xe9a1a3b0  0xe9a24cf4  Yes (*)     /lib/i386-linux-gnu/libXext.so.6
0xe9a0c5f0  0xe9a11604  Yes (*)     /lib/i386-linux-gnu/libXcursor.so.1
0xe9d07110  0xe9d07b34  Yes (*)     /lib/i386-linux-gnu/libXinerama.so.1
0xe961a250  0xe9624cb4  Yes (*)     /lib/i386-linux-gnu/libXi.so.6
0xe960c5e0  0xe9612cd4  Yes (*)     /lib/i386-linux-gnu/libXrandr.so.2
0xe9d02160  0xe9d02e94  Yes (*)     /lib/i386-linux-gnu/libXss.so.1
0xe9a03bd0  0xe9a06584  Yes (*)     /lib/i386-linux-gnu/libXxf86vm.so.1
0xe93ec5a0  0xe93f6314  Yes (*)     /lib/i386-linux-gnu/libdrm.so.2
0xe93db460  0xe93e1d24  Yes (*)     /lib/i386-linux-gnu/libgbm.so.1
0xe9607060  0xe9607275  Yes (*)     /lib/i386-linux-gnu/libwayland-egl.so.1
0xe93cc460  0xe93d1394  Yes (*)     /lib/i386-linux-gnu/libwayland-client.so.0
0xe93c0270  0xe93c2154  Yes (*)     /lib/i386-linux-gnu/libwayland-cursor.so.0
0xe937b510  0xe9397984  Yes (*)     /lib/i386-linux-gnu/libxkbcommon.so.0
0xe8981f30  0xe89c6574  Yes (*)     /usr/lib/i386-linux-gnu/pulseaudio/libpulsecommon-14.2.so
0xe9321d40  0xe9352134  Yes (*)     /lib/i386-linux-gnu/libdbus-1.so.3
0xe8c4e720  0xe8c63c24  Yes (*)     /lib/i386-linux-gnu/libxcb.so.1
0xe930b430  0xe93117f4  Yes (*)     /lib/i386-linux-gnu/libXrender.so.1
0xe93031a0  0xe93056e4  Yes (*)     /lib/i386-linux-gnu/libXfixes.so.3
0xe8c33640  0xe8c3a794  Yes (*)     /lib/i386-linux-gnu/libwayland-server.so.0
0xe8c03130  0xe8c1f024  Yes (*)     /lib/i386-linux-gnu/libexpat.so.1
0xe8968250  0xe896c8c4  Yes (*)     /lib/i386-linux-gnu/libffi.so.7
0xe7f45a80  0xe7fbed44  Yes (*)     /lib/i386-linux-gnu/libsystemd.so.0
0xe895d6e0  0xe8961424  Yes (*)     /lib/i386-linux-gnu/libwrap.so.0
0xe7ea49c0  0xe7f05f34  Yes (*)     /lib/i386-linux-gnu/libsndfile.so.1
0xe8954250  0xe89569a4  Yes (*)     /lib/i386-linux-gnu/libasyncns.so.0
0xe9602200  0xe9602f94  Yes (*)     /lib/i386-linux-gnu/libXau.so.6
0xe894cea0  0xe894e914  Yes (*)     /lib/i386-linux-gnu/libXdmcp.so.6
0xe8922510  0xe893bcd4  Yes (*)     /lib/i386-linux-gnu/liblzma.so.5
0xe7dd95a0  0xe7e845a4  Yes (*)     /lib/i386-linux-gnu/libzstd.so.1
0xe853e2f0  0xe8559432  Yes (*)     /lib/i386-linux-gnu/liblz4.so.1
0xe7cee560  0xe7d77e94  Yes (*)     /lib/i386-linux-gnu/libgcrypt.so.20
0xe8908980  0xe8914d04  Yes (*)     /lib/i386-linux-gnu/libnsl.so.2
0xe85088f0  0xe852bd54  Yes (*)     /lib/i386-linux-gnu/libFLAC.so.8
0xe7cbe550  0xe7cd2284  Yes (*)     /lib/i386-linux-gnu/libvorbis.so.0
0xe7c360b0  0xe7c387a4  Yes (*)     /lib/i386-linux-gnu/libvorbisenc.so.2
0xe7bd4350  0xe7c16594  Yes (*)     /lib/i386-linux-gnu/libopus.so.0
0xe7bc8260  0xe7bcb2c4  Yes (*)     /lib/i386-linux-gnu/libogg.so.0
0xe7bb18b0  0xe7bbd924  Yes (*)     /lib/i386-linux-gnu/libbsd.so.0
0xe7b896a0  0xe7b9d784  Yes (*)     /lib/i386-linux-gnu/libgpg-error.so.0
0xe7b581a0  0xe7b737b4  Yes (*)     /lib/i386-linux-gnu/libtirpc.so.3
0xe7b44430  0xe7b4b824  Yes (*)     /lib/i386-linux-gnu/libmd.so.0
0xe7af0510  0xe7b25204  Yes (*)     /lib/i386-linux-gnu/libgssapi_krb5.so.2
0xe7a20820  0xe7a80b54  Yes (*)     /lib/i386-linux-gnu/libkrb5.so.3
0xe79dc590  0xe79f8374  Yes (*)     /lib/i386-linux-gnu/libk5crypto.so.3
0xe89012c0  0xe8901fa4  Yes (*)     /lib/i386-linux-gnu/libcom_err.so.2
0xe79cc640  0xe79d2bc4  Yes (*)     /lib/i386-linux-gnu/libkrb5support.so.0
0xe79c3270  0xe79c45d4  Yes (*)     /lib/i386-linux-gnu/libkeyutils.so.1
0xeceadd90  0xeceaed08  Yes (*)     cstrike/addons/amxmodx/modules/sockets_amxx_i386.so
0xeca65350  0xeca6dfc8  Yes (*)     cstrike/addons/amxmodx/modules/regex_amxx_i386.so
(*): Shared library is missing debugging information.
Stack level 0, frame at 0xff8be1a0:
 eip = 0xf75248e0 in Cache_TryAlloc (/home/natasha/rehlds/rehlds/engine/zone.cpp:647); saved eip = 0xf75658b1
 inlined into frame 1
 source language c++.
 Arglist at unknown address.
 Locals at unknown address, Previous frame's sp in esp
End of crash report
```

**Comment by natashasrcz** [comment]
any reason for that? as it is random crash and the above model works fine if rehlds does not crash

**Comment by PM32** [comment]
Model you provided has more than 300 sequences, if you are not using sequences above seqid 110 then crop all the remaining sequences

**Comment by natashasrcz** [comment]
is there any hard limit for sequences? does it apply to rehlds only?
